### ISSUE TITLE
c-extension intruduced by yargs is a hazard

### ISSUE THREAD

**Issue by stefanpenner** [calvinmetcalf/derequire#29]
via os-local https://github.com/sindresorhus/os-locale/blob/master/package.json#L2

just by requiring this as a lib, a user is required to have a working compiler toolchain, and portability between various nodes becomes dubious.

**Comment by calvinmetcalf** [comment]
are you talking about [exec-file-sync](]https://github.com/sindresorhus/exec-file-sync)? I think that only is required for version 0.10

**Comment by zertosh** [comment]
This was fixed by https://github.com/sindresorhus/os-locale/pull/11

**Comment by nexdrew** [comment]
Also, latest version of `yargs` (3.23.0) should fix this as well. We replaced the dependency on `os-locale` with a [locally ported version](https://github.com/bcoe/yargs/pull/246) that only uses environment variables, as a stop-gap solution until a proper fix could be applied to `os-locale`. As @zertosh mentioned, the fix has been merged into `os-locale`, but we're waiting for the next release to apply it back to `yargs`.

Sorry for the problems and confusion! This is something we take very seriously, and we're adding additional measures to our testing to avoid this in the future. Either way, you should be good with `yargs@>=3.23.0`, including fresh installs of `derequire` (since 2015-08-31T06:14:10.463Z).

**Comment by calvinmetcalf** [comment]
@nexdrew great thanks for the quick fix!

**Comment by stefanpenner** [comment]
Awesome. Thanks all!

**Comment by nexdrew** [comment]
@stefanpenner @calvinmetcalf @zertosh Just to keep everyone updated, `yargs@3.24.0` has been published and includes the `os-locale` fix. No more `exec-file-sync`! :tada:
